openapi: 3.0.0
info:
  title: Extension Specification
  version: 1.0.0
servers:
  - url: /
paths:
  /test:
    get:
      summary: Get the test resource
      x-test-extension: "true"
      responses:
        "200":
          description: Everything is ok
